"""initial schema

Revision ID: 746f24b87002
Revises:
Create Date: 2026-09-06 19:17:06.910341
"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "746f24b87002"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("careers_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "adapter_type",
            sa.Enum(
                "GREENHOUSE",
                "LEVER",
                "ASHBY",
                "WORKABLE",
                "RECRUITEE",
                "PERSONIO",
                "SMARTRECRUITERS",
                "JSONLD",
                "SITEMAP",
                "LLM",
                "UNKNOWN",
                name="adaptertype",
            ),
            nullable=False,
        ),
        sa.Column("adapter_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "NEEDS_REVIEW", "ACTIVE", "FAILED", "REJECTED", name="companystatus"
            ),
            nullable=False,
        ),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detection_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detection_confidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detection_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("consecutive_empty_results", sa.Integer(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_adapter_type"), "company", ["adapter_type"], unique=False)
    op.create_index(op.f("ix_company_domain"), "company", ["domain"], unique=True)
    op.create_index(op.f("ix_company_name"), "company", ["name"], unique=False)
    op.create_index(op.f("ix_company_status"), "company", ["status"], unique=False)
    op.create_table(
        "discovery_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="candidatestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_candidate_domain"), "discovery_candidate", ["domain"], unique=True
    )
    op.create_index(
        op.f("ix_discovery_candidate_status"), "discovery_candidate", ["status"], unique=False
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cv_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cv_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cv_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_only", sa.Boolean(), nullable=False),
        sa.Column("hours_old", sa.Integer(), nullable=False),
        sa.Column("results_wanted", sa.Integer(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_profile_name"), "search_profile", ["name"], unique=True)
    op.create_table(
        "usage_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_creation_input_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_input_tokens", sa.Integer(), nullable=False),
        sa.Column("batch", sa.Boolean(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usage_log_agent"), "usage_log", ["agent"], unique=False)
    op.create_index(op.f("ix_usage_log_created_at"), "usage_log", ["created_at"], unique=False)
    op.create_table(
        "discovery_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="discoveryrunstatus"),
            nullable=False,
        ),
        sa.Column("found_count", sa.Integer(), nullable=False),
        sa.Column("new_count", sa.Integer(), nullable=False),
        sa.Column("source_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["search_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_run_created_at"), "discovery_run", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_discovery_run_profile_id"), "discovery_run", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_discovery_run_status"), "discovery_run", ["status"], unique=False)
    op.create_table(
        "job_posting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "remote_type",
            sa.Enum("ONSITE", "HYBRID", "REMOTE", "UNKNOWN", name="remotetype"),
            nullable=False,
        ),
        sa.Column("seniority", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("employment_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description_md", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "apply_channel",
            sa.Enum("EMAIL", "ATS_FORM", "EXTERNAL", "UNKNOWN", name="applychannel"),
            nullable=False,
        ),
        sa.Column("apply_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("apply_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "source_adapter",
            sa.Enum(
                "GREENHOUSE",
                "LEVER",
                "ASHBY",
                "WORKABLE",
                "RECRUITEE",
                "PERSONIO",
                "SMARTRECRUITERS",
                "JSONLD",
                "SITEMAP",
                "LLM",
                "UNKNOWN",
                name="adaptertype",
            ),
            nullable=False,
        ),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "external_id", name="uq_job_company_ext"),
    )
    op.create_index(op.f("ix_job_posting_company_id"), "job_posting", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_job_posting_external_id"), "job_posting", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_posting_first_seen_at"), "job_posting", ["first_seen_at"], unique=False
    )
    op.create_table(
        "job_lead",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "remote_type",
            sa.Enum("ONSITE", "HYBRID", "REMOTE", "UNKNOWN", name="remotetype"),
            nullable=False,
        ),
        sa.Column("description_md", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("apply_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "SHORTLISTED", "DISMISSED", name="jobleadstatus"),
            nullable=False,
        ),
        sa.Column("last_run_id", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_run_id"],
            ["discovery_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_lead_company_name"), "job_lead", ["company_name"], unique=False)
    op.create_index(op.f("ix_job_lead_fingerprint"), "job_lead", ["fingerprint"], unique=True)
    op.create_index(op.f("ix_job_lead_first_seen_at"), "job_lead", ["first_seen_at"], unique=False)
    op.create_index(op.f("ix_job_lead_last_run_id"), "job_lead", ["last_run_id"], unique=False)
    op.create_index(op.f("ix_job_lead_status"), "job_lead", ["status"], unique=False)
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("prefilter_passed", sa.Boolean(), nullable=False),
        sa.Column("prefilter_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("embedding_score", sa.Float(), nullable=True),
        sa.Column("llm_score", sa.Integer(), nullable=True),
        sa.Column("rationale", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "SHORTLISTED", "DISMISSED", "APPROVED", "SENT", name="matchstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_posting.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "profile_id", name="uq_match_job_profile"),
    )
    op.create_index(op.f("ix_match_job_id"), "match", ["job_id"], unique=False)
    op.create_index(op.f("ix_match_llm_score"), "match", ["llm_score"], unique=False)
    op.create_index(op.f("ix_match_profile_id"), "match", ["profile_id"], unique=False)
    op.create_index(op.f("ix_match_status"), "match", ["status"], unique=False)
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("tailored_cv_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cover_letter", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "ATS_FORM", "EXTERNAL", "UNKNOWN", name="applychannel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "APPROVED", "SENT", "REPLIED", "REJECTED", name="applicationstatus"),
            nullable=False,
        ),
        sa.Column("gmail_draft_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gmail_thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_application_match_id"), "application", ["match_id"], unique=True)
    op.create_index(op.f("ix_application_status"), "application", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_status"), table_name="application")
    op.drop_index(op.f("ix_application_match_id"), table_name="application")
    op.drop_table("application")
    op.drop_index(op.f("ix_match_status"), table_name="match")
    op.drop_index(op.f("ix_match_profile_id"), table_name="match")
    op.drop_index(op.f("ix_match_llm_score"), table_name="match")
    op.drop_index(op.f("ix_match_job_id"), table_name="match")
    op.drop_table("match")
    op.drop_index(op.f("ix_job_lead_status"), table_name="job_lead")
    op.drop_index(op.f("ix_job_lead_last_run_id"), table_name="job_lead")
    op.drop_index(op.f("ix_job_lead_first_seen_at"), table_name="job_lead")
    op.drop_index(op.f("ix_job_lead_fingerprint"), table_name="job_lead")
    op.drop_index(op.f("ix_job_lead_company_name"), table_name="job_lead")
    op.drop_table("job_lead")
    op.drop_index(op.f("ix_job_posting_first_seen_at"), table_name="job_posting")
    op.drop_index(op.f("ix_job_posting_external_id"), table_name="job_posting")
    op.drop_index(op.f("ix_job_posting_company_id"), table_name="job_posting")
    op.drop_table("job_posting")
    op.drop_index(op.f("ix_discovery_run_status"), table_name="discovery_run")
    op.drop_index(op.f("ix_discovery_run_profile_id"), table_name="discovery_run")
    op.drop_index(op.f("ix_discovery_run_created_at"), table_name="discovery_run")
    op.drop_table("discovery_run")
    op.drop_index(op.f("ix_usage_log_created_at"), table_name="usage_log")
    op.drop_index(op.f("ix_usage_log_agent"), table_name="usage_log")
    op.drop_table("usage_log")
    op.drop_index(op.f("ix_search_profile_name"), table_name="search_profile")
    op.drop_table("search_profile")
    op.drop_table("profile")
    op.drop_index(op.f("ix_discovery_candidate_status"), table_name="discovery_candidate")
    op.drop_index(op.f("ix_discovery_candidate_domain"), table_name="discovery_candidate")
    op.drop_table("discovery_candidate")
    op.drop_index(op.f("ix_company_status"), table_name="company")
    op.drop_index(op.f("ix_company_name"), table_name="company")
    op.drop_index(op.f("ix_company_domain"), table_name="company")
    op.drop_index(op.f("ix_company_adapter_type"), table_name="company")
    op.drop_table("company")
    for enum_name in (
        "applicationstatus",
        "matchstatus",
        "jobleadstatus",
        "applychannel",
        "remotetype",
        "discoveryrunstatus",
        "candidatestatus",
        "companystatus",
        "adaptertype",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
    # ### end Alembic commands ###
